# -*- coding: utf-8 -*-
"""Smart ATM Cash Demand Forecasting Using LSTM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-S9A_5sPASuIqsXaEehI2TU-Sy5vKqyK
"""

# Commented out IPython magic to ensure Python compatibility.
# ==========================================
# Import Required Libraries
# Smart ATM Cash Demand Forecasting Using LSTM
# ==========================================

# Data Manipulation
import pandas as pd
import numpy as np

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Ignore Warnings
import warnings
warnings.filterwarnings("ignore")

# Date and Time
from datetime import datetime

# Data Preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# Evaluation Metrics
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    mean_absolute_percentage_error,
    r2_score
)

# Deep Learning
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# %matplotlib inline

print("Libraries Imported Successfully")

# ==========================================
# Load Dataset
# ==========================================

df = pd.read_csv("/content/Smart_ATM_Cash_Demand_Dataset.csv")

df.head()

print("Dataset Shape :", df.shape)

df.info()

df.describe(include="all")

df.isnull().sum()

df.duplicated().sum()

print(df.columns.tolist())

"""Select One ATM


"""

#Display Available ATM IDs
print(df["atmId"].unique())
#Count Number of ATMs
print("Total ATMs :", df["atmId"].nunique())
#Display Transactions per ATM
df["atmId"].value_counts()

selected_atm = "ATM001"

atm_df = df[df["atmId"] == selected_atm].copy()

print("Selected ATM :", selected_atm)
print("Total Records :", len(atm_df))

#Display First Five Records
atm_df.head()
#Check Missing Values
atm_df.isnull().sum()
#Remove Duplicate Records
atm_df = atm_df.drop_duplicates()

print("Dataset Shape :", atm_df.shape)

# ==========================================
# Feature Engineering
# Smart ATM Cash Demand Forecasting Using LSTM
# ==========================================

# Convert transactionTime to datetime format
atm_df["transactionTime"] = pd.to_datetime(atm_df["transactionTime"])

print("Transaction Time Data Type:")
print(atm_df["transactionTime"].dtype)

# --------------------------------------------------
# Sort the dataset in chronological order
# --------------------------------------------------

atm_df = atm_df.sort_values("transactionTime")
atm_df = atm_df.reset_index(drop=True)

print("\nDataset Sorted Successfully")

# --------------------------------------------------
# Extract Time-Based Features
# --------------------------------------------------

atm_df["Year"] = atm_df["transactionTime"].dt.year
atm_df["Month"] = atm_df["transactionTime"].dt.month
atm_df["Day"] = atm_df["transactionTime"].dt.day
atm_df["Hour"] = atm_df["transactionTime"].dt.hour
atm_df["DayOfWeek"] = atm_df["transactionTime"].dt.dayofweek
atm_df["Week"] = atm_df["transactionTime"].dt.isocalendar().week.astype(int)

print("\nTime-Based Features Created Successfully")

# --------------------------------------------------
# Display First Five Records
# --------------------------------------------------

print("\nFirst Five Records")
display(atm_df.head())

# --------------------------------------------------
# Display Dataset Information
# --------------------------------------------------

print("\nDataset Information")
atm_df.info()

# --------------------------------------------------
# Statistical Summary
# --------------------------------------------------

print("\nStatistical Summary")
display(atm_df.describe())

# --------------------------------------------------
# Display Date Range
# --------------------------------------------------

print("\nDate Range")
print("Start Date :", atm_df["transactionTime"].min())
print("End Date   :", atm_df["transactionTime"].max())

# --------------------------------------------------
# Check Missing Values
# --------------------------------------------------

print("\nMissing Values")
display(atm_df.isnull().sum())

# --------------------------------------------------
# Select Target Variable
# --------------------------------------------------

cash_demand = atm_df[["transactionTime", "totalOutcome"]]

print("\nCash Demand Dataset")
display(cash_demand.head())

# --------------------------------------------------
# Display Dataset Shape
# --------------------------------------------------

print("\nCash Demand Dataset Shape :", cash_demand.shape)

# =====================================================
# Data Preprocessing
# =====================================================

from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Select only the target column
data = df[['totalOutcome']].values

# Normalize the data (0 to 1)
scaler = MinMaxScaler(feature_range=(0,1))
scaled_data = scaler.fit_transform(data)

print("Scaled Data Shape :", scaled_data.shape)
print("\nFirst 5 Scaled Values")
print(scaled_data[:5])

# =====================================================
# Create Time Series Sequences
# =====================================================

sequence_length = 24

X = []
y = []

for i in range(sequence_length, len(scaled_data)):
    X.append(scaled_data[i-sequence_length:i,0])
    y.append(scaled_data[i,0])

X = np.array(X)
y = np.array(y)

print("X Shape :", X.shape)
print("y Shape :", y.shape)

# =====================================================
# Reshape for LSTM
# =====================================================

X = np.reshape(X, (X.shape[0], X.shape[1], 1))

print("Reshaped X :", X.shape)

# =====================================================
# Train Test Split
# =====================================================

split = int(len(X)*0.8)

X_train = X[:split]
X_test = X[split:]

y_train = y[:split]
y_test = y[split:]

print("Training Samples :", X_train.shape)
print("Testing Samples  :", X_test.shape)

# =====================================================
# Build the LSTM Model
# =====================================================

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential()

model.add(LSTM(64, return_sequences=True,
               input_shape=(X_train.shape[1],1)))
model.add(Dropout(0.2))

model.add(LSTM(64))
model.add(Dropout(0.2))

model.add(Dense(25))
model.add(Dense(1))

model.compile(
    optimizer='adam',
    loss='mean_squared_error'
)

model.summary()

# =====================================================
# Train the Model
# =====================================================

history = model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_test,y_test),
    verbose=1
)

"""Predict Cash Demand"""

# =====================================================
# Predict
# =====================================================

predictions = model.predict(X_test)

# Convert back to original values
predictions = scaler.inverse_transform(predictions.reshape(-1,1))
actual = scaler.inverse_transform(y_test.reshape(-1,1))

"""Visualize Predictions"""

# =====================================================
# Actual vs Predicted
# =====================================================

import matplotlib.pyplot as plt

plt.figure(figsize=(16,6))

plt.plot(actual,label='Actual Cash Demand')
plt.plot(predictions,label='Predicted Cash Demand')

plt.title("ATM Cash Demand Forecast")
plt.xlabel("Time")
plt.ylabel("Cash Withdrawal Amount")
plt.legend()

plt.show()

# =====================================================
# Evaluation
# =====================================================

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import numpy as np

mae = mean_absolute_error(actual,predictions)

rmse = np.sqrt(
    mean_squared_error(actual,predictions)
)

r2 = r2_score(actual,predictions)

print("Model Evaluation")
print("------------------------")
print("MAE  :", round(mae,2))
print("RMSE :", round(rmse,2))
print("R² Score :", round(r2,4))

# =====================================================
# Training Loss
# =====================================================

plt.figure(figsize=(10,5))

plt.plot(history.history['loss'],label='Training Loss')
plt.plot(history.history['val_loss'],label='Validation Loss')

plt.title("Training vs Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()

plt.show()

# =====================================================
# Forecast Next 24 Hours
# =====================================================

last_sequence = scaled_data[-24:]
current_sequence = last_sequence.reshape(1,24,1)

future_predictions = []

for i in range(24):

    pred = model.predict(current_sequence, verbose=0)

    future_predictions.append(pred[0,0])

    current_sequence = np.append(
        current_sequence[:,1:,:],
        [[[pred[0,0]]]],
        axis=1
    )

future_predictions = scaler.inverse_transform(
    np.array(future_predictions).reshape(-1,1)
)

print("Next 24 Hours Cash Demand Forecast")

for i,value in enumerate(future_predictions):
    print(f"Hour {i+1}: ₹{value[0]:,.2f}")

# =====================================================
# Future Forecast Graph
# =====================================================

plt.figure(figsize=(12,5))

plt.plot(
    range(1,25),
    future_predictions,
    marker='o'
)

plt.title("Next 24 Hours ATM Cash Demand Forecast")
plt.xlabel("Future Hour")
plt.ylabel("Predicted Cash Withdrawal Amount")

plt.grid(True)

plt.show()

# =====================================================
# Save LSTM Model
# =====================================================

model.save("atm_cash_lstm_model.keras")

print("Model saved successfully.")

# =====================================================
# Save Scaler
# =====================================================

import joblib

joblib.dump(scaler, "cash_scaler.pkl")

print("Scaler saved successfully.")

# =====================================================
# Load Model
# =====================================================

from tensorflow.keras.models import load_model

loaded_model = load_model("atm_cash_lstm_model.keras")

print("Model loaded successfully.")

# =====================================================
# Load Model
# =====================================================

from tensorflow.keras.models import load_model

loaded_model = load_model("atm_cash_lstm_model.keras")

print("Model loaded successfully.")

# =====================================================
# Load Scaler
# =====================================================

loaded_scaler = joblib.load("cash_scaler.pkl")

print("Scaler loaded successfully.")

# =====================================================
# Prediction Using Saved Model
# =====================================================

last_sequence = scaled_data[-24:]
last_sequence = last_sequence.reshape(1,24,1)

prediction = loaded_model.predict(last_sequence)

prediction = loaded_scaler.inverse_transform(prediction)

print("Predicted Next Hour Cash Demand : ₹", round(prediction[0][0],2))

# =====================================================
# Download Files
# =====================================================

from google.colab import files

files.download("atm_cash_lstm_model.keras")
files.download("cash_scaler.pkl")

from tensorflow.keras.models import load_model

model = load_model("atm_cash_lstm_model.keras")

print("Input Shape :", model.input_shape)
print("Output Shape:", model.output_shape)

model.summary()